# Generated by Django 4.0.5 on 2022-07-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(default='None', max_length=200, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='subCategory')),
                ('name', models.CharField(default='None', max_length=200, verbose_name='Sub-category Name')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mainMenu')),
                ('title', models.CharField(max_length=100)),
                ('upload_date', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=55, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='SubcatName',
            field=models.ManyToManyField(related_name='subcat', to='home.subcategory', verbose_name='Sub-category Name'),
        ),
    ]
